HOST = "localhost"
PORT = 50051

RECONNECT_BACKOFF = [1, 2, 4, 8, 16, 30]
RECONNECT_TOTAL_S = 60

KEEPALIVE_MS = 20000
KEEPALIVE_TIMEOUT_MS = 10000

CATEGORIES = [
    "BMS", "ENGINE", "CHARGER", "COOLING", "LIGHTS",
    "SENSORS", "DASHBOARD", "PEDALS", "POWER", "NODE_STATUS",
]
